# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'UnityWithCameraKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnityWithCameraKit

  pod 'Alamofire', '~> 5.4'
  pod 'SCCameraKit', '1.46.0'
  pod 'SCCameraKitReferenceUI', '1.46.0'
  pod 'SCCameraKitReferenceSwiftUI', '1.46.0'
  
  target 'UnityWithCameraKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnityWithCameraKitUITests' do
    # Pods for testing
  end

end
